### PR TITLE
Update - Add animation image rotate

### PR DESCRIPTION
**Pull request by degraphic**
Update - Add animation image rotate

### CODE REVIEW

**Comment by dedywahyudi** [comment]
@degraphic Your PR have conflicts. Pull latest master to your branch

**Comment by dedywahyudi** [comment]
@degraphic i'm still not see the cursor: pointer for Download Results and Recalculate button

**Comment by degraphic** [comment]
> @degraphic i'm still not see the cursor: pointer for Download Results and Recalculate button
@dedywahyudi 
I have add it on this
https://github.com/topcoder-platform/taas-roi-calculator/pull/12

**Comment by dedywahyudi** [comment]
@degraphic We still need this PR? This one have conflicts

**Comment by degraphic** [comment]
@dedywahyudi i think no need this PR, i will deleted it

**Pull request closed without merging**
